---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: infra-machine-autoscaler-a
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ infraID }}-infra-{{ regionID }}a

---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: infra-machine-autoscaler-b
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ infraID }}-infra-{{ regionID }}b
    
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: infra-machine-autoscaler-c
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ infraID }}-infra-{{ regionID }}c
