---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ infraID }}
  name: {{ infraID }}-infra-{{ regionID }}a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ infraID }}
      machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ infraID }} 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: infra
          value: reserved
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ infraID }}-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ regionID }}a
            region: {{ regionID }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ infraID }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ infraID }}-private-{{ regionID }}a 
          tags:
            - name: kubernetes.io/cluster/{{ infraID }}
              value: owned
          userDataSecret:
            name: worker-user-data
            
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ infraID }}
  name: {{ infraID }}-infra-{{ regionID }}b
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ infraID }}
      machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ infraID }} 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}b
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: infra
          value: reserved
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ infraID }}-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ regionID }}b
            region: {{ regionID }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ infraID }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ infraID }}-private-{{ regionID }}b
          tags:
            - name: kubernetes.io/cluster/{{ infraID }}
              value: owned
          userDataSecret:
            name: worker-user-data
            
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ infraID }}
  name: {{ infraID }}-infra-{{ regionID }}c
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ infraID }}
      machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ infraID }} 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: {{ infraID }}-infra-{{ regionID }}c
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: infra
          value: reserved
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: ami-078e26f293629fe91
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ infraID }}-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ regionID }}c
            region: {{ regionID }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ infraID }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ infraID }}-private-{{ regionID }}c
          tags:
            - name: kubernetes.io/cluster/{{ infraID }}
              value: owned
          userDataSecret:
            name: worker-user-data
