image::https://github.com/r3dact3d/OCP4-Deploy/actions/workflows/deploy.yaml/badge.svg[link="https://github.com/r3dact3d/OCP4-Deploy/actions/workflows/deploy.yaml"]

image::https://github.com/r3dact3d/OCP4-Deploy/actions/workflows/destroy.yaml/badge.svg[link="https://github.com/r3dact3d/OCP4-Deploy/actions/workflows/destroy.yaml"]


= Repo for deploying OCP to AWS

NOTE: *fork* or *clone* repo so that you can use Your own GitHub Secrets and worklflow.

== Content

* <<Workflow, Workflow>>
* <<Important, Important>>
* <<TODO, TODO>>

== Workflow

=== To deploy OCP4.x

. Ensure GitHub Secrets are created and up-to-date
.. OCP_ADMIN_USER is the cluster admin username
.. OCP_ADMIN_PASS 
.. OCP_DEV_USER
.. OCP_DEV_PASS 
.. OCP_BASE_DOMAIN is the top level route53 domain
.. OCP_CLUSTER_NAME
.. OCP_CLIENT_VERSION will be the version of OpenShift "4", "4.7", or "4.9.9"
.. RED_HAT_PULLSECRET is the required Red Hat creds for their repositories
.. AWS_ACCESS_KEY_ID is the AWS Access Key
.. AWS_SECRET_ACCESS_KEY is the AWS Secret Access key
.. AWS_REGION

NOTE: You can now check the Actions to watch/check the status of the deployment.  Also, the latest stable version of OpenShift 4 will be deployed.  This can be updated or changed in the workflow deploy file.

==== Actions

Upon successful merge to main of deploy.md file, the workflow will automatically kick off.

. Perform AWS IPI 
. Creates an Artifact for Destroy
.. You can download artifact if needed from GitHub Actions > Runs
.. Double check your retention period for Artifacts
. Setup HTPasswd IDP
.. Uses CLUSTER_ADMIN and ADMIN_PASS
.. Uses DEV_PASS for andrew the developer
. Install GitOps Operator
.. Sets admin password for console to ADMIN_PASS

==== Important

* During the *deploy* workflow the artifacts describing the AWS resources that are deployed are needed for the *destroy* workflow.  
* The artifacts are uploaded for only 90 days and will need to be *manually* downloaded if it's not planned to *destroy* the cluster within that retention period.

=== To destroy OCP4.x

. Push or Merge change to destroy.md

This will kick off the destroy workflow, pulling the artifact from deploy workflow automatically and destroying the AWS resources.





== TODO

* Add OCP openshift-installer version as variable




NOTE: GitHub IDP is disabled currently

=== GitHub IDP

* GitHub IDP is used in this deploy, so a GitHub organization should be created
* Add the clientSecret to GitHub Secrets as CLIENT_SECRET
* Update the GitHub Organization name and clientID in idp-oauth.yaml file
